### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by aruhela** [LLNL/mpiP#20]
Hi,

I am using topic/mt branch for profiling communication through threads in MVAPICH2. 

Two issues.
1. I cannot checkout topic/mt branch unless I delete mpiPi.h file
2. The compilation fails saying following.
checking whether MPI_Init is declared... no
configure: error: "Failed to find declaration for MPI_Init!"

Is the topic/mt branch still under testing or what branch should I use for thread profiling?

Thanks
Amit

**Comment by aruhela** [comment]
Solved by referring followng thread
https://sourceforge.net/p/mpip/mailman/mpip-help/thread/2014050923032598511118@gmail.com/

./configure --prefix=$PWD/build CC=mpicc CXX=mpicxx CFLAGS=-fPIC --disable-bfd --disable-libunwind CPPFLAGS="-I/home/ruhela.2/libs/MvapXIc/mvapich2/build/lib"
make install 
make shared

**Comment by artpol84** [comment]
@aruhela

Please share your experience with topic/mt
I’m trying to push this upstream and your input would be very valuable.

The thread is indeed in the testing state, but I successfully used it for a number of production grade apps

**Comment by aruhela** [comment]
Dear Artem,

I am able to build it(branch 96f9433...) with MVAPICH2 and used the same to
profile "madness" mpi application. So far, the results look good.

Thanks,
Amit Ruhela
