### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by vitlav** [LLNL/mpiP#25]
Please set a tag with new version on the stable commit.

**Comment by bhatele** [comment]
@cchambreau Are there plans to do a new release of mpiP? the 3.4.1 release does not have the make-wrappers fixes. So the spack build fails when trying to build the 3.4.1 version

**Comment by cchambreau** [comment]
@bhatele Hoping to have something available by mid-October.

**Comment by surak** [comment]
It's mid-october :-)

**Comment by cchambreau** [comment]
POWER multi-threaded testing issue resolved.  Release 3.5 completed.  I'll take a look at updating spack to point to the new release.

**Comment by surak** [comment]
Thanks. Already installed on the JUWELS supercomputer!
